; ========================================================
; Archivo de configuración de base de datos de ejemplo
; ========================================================
;
; Renombrar este archivo a "dbconfig.ini" y completarlo con
; los datos reales del entorno de producción. Este archivo (dbconfig.ini)
; no se subirá al repositorio porque está ignorado.
;
; Nota: Las secciones entre corchetes son los "dbKey" que usa DataAccess.cs.
; También puedes definir otras variables sueltas como LinkedServerPassword
; que son cargadas por el programa.

; Contraseña utilizada para crear el servidor vinculado (Linked Server) hacia los puntos de venta
LinkedServerPassword=TU_PASSWORD_AQUI

[MOSTAZA_ERP]
ConnectionString=Server=172.16.0.34;Database=MOSTAZA_ERP;User Id=sa;Password=TU_PASSWORD_AQUI;

[GMG_ERP]
ConnectionString=Server=172.16.0.34;Database=GMG_ERP;User Id=sa;Password=TU_PASSWORD_AQUI;
